name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Java 21 (avec cache Maven)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compiler le projet
        run: mvn -B package -DskipTests

      - name: Vérifier le JAR
        run: ls -lh target/*.jar

      - name: Téléverser le JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar
          retention-days: 7

  unit-tests:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Java 21 (avec cache Maven)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Télécharger le JAR (artifact)
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: target

      - name: Vérifier le JAR
        run: ls -lh target/*.jar

      - name: Lancer les tests unitaires
        run: mvn -B test
